#!/bin/bash

HISTORY="$HOME/.local/share/mpv_history/history"
SEPARATOR="##@@##@@##"
PICKER="rofi -dmenu -i -p"

# create storage if doesnt exist
[ -f "$HISTORY" ] \
    || ( mkdir -p $(dirname "$HISTORY") && touch "$HISTORY" )

# clean db
if [[ $1 == '--clear' ]]; then
    backup=/tmp/mpv_history.backup
    cp $HISTORY $backup
    echo -n "" > $HISTORY
    notify-send -u critical -t 1500 "MPV history" "cleared all records (moved them to $backup)"
    exit 0
fi

# empty db
if [[ $(cat $HISTORY | wc -l) -eq 0 ]]; then
    notify-send -t 1500 "MPV history" "Empty"
    exit 0
fi

CLIPBOARD=0
HANDLER=0
# change prompt based on type
if [ "$1" = "-c" ] || [ "$1" = "--clipboard" ]; then
    prompt="clipboard  "
    CLIPBOARD=1
elif [ "$1" = "-h" ] || [ "$1" = "--handler" ]; then
    [ $# -lt 2 ] && echo "specify handler" && exit 1
    # use first handler argument as label
    prompt="$(echo $2 | tr '[:lower:]' '[:upper:]')  "
    HANDLER=1
else
    prompt="HISTORY  "
fi

# pick
chosen=$(tac $HISTORY | sed "s/\s$SEPARATOR.*//" | $PICKER "$prompt: ")

[[ $chosen == '' ]] && exit 1
chosen=$(cat $HISTORY | grep "$chosen" | head -n 1)

# separate line
title=$(echo $chosen | sed "s/\s$SEPARATOR.*//")
url=$(echo $chosen | sed "s/.*\($SEPARATOR\)\s//")

# perform action
if [ "$CLIPBOARD" -eq 1 ]; then
    echo "$url" | wl-copy
    notify-send -i 'none' "Clipboard content" "$url"
    # we dont alter history when copying to clipboard
    exit 0
elif [ "$HANDLER" -eq 1 ]; then
    # run all remaining arguments
    shift
    "$@" "$url"
else
    mpv "$url"
fi

# remove picked line from history and add it to beginning
cat $HISTORY | awk -vLine="$chosen" '!index($0,Line)' > /tmp/history
cat /tmp/history > $HISTORY
echo "$chosen" >> $HISTORY
