#!/bin/bash

HISTORY="$HOME/.local/share/mpv_history/history"
SEPARATOR="##@@##@@##"

FUZZEL="fuzzel -l 25 -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d -w 70"

# create storage if doesnt exist
[ -f "$HISTORY" ] \
    || ( mkdir -p $(dirname "$HISTORY") && touch "$HISTORY" )

# clean db
if [[ $1 == '--clear' ]]; then
    backup=/tmp/mpv_history.backup
    cp $HISTORY $backup
    echo -n "" > $HISTORY
    notify-send -u critical -t 1500 "MPV history" "cleared all records (moved them to $backup)"
    exit 0
fi

# empty db
if [[ $(cat $HISTORY | wc -l) -eq 0 ]]; then
    notify-send -t 1500 "MPV history" "Empty"
    exit 0
fi

# change prompt based on type

if [ "$1" = "--clipboard" ]; then
    prompt="clipboard  "
elif [ "$1" = "-h" ] || [ "$1" = "--handler" ]; then
    [ $# -lt 2 ] && echo "specify handler" && exit 1
    # use first handler argument as label
    prompt="$(echo $2 | tr '[:lower:]' '[:upper:]')  "
else
    prompt="HISTORY  "
fi

# pick using fuzzel
chosen=$(tac $HISTORY | sed "s/\s$SEPARATOR.*//" | $FUZZEL -P "$prompt: ")

[[ $chosen == '' ]] && exit 1
chosen=$(cat $HISTORY | grep "$chosen" | head -n 1)

# separate line
title=$(echo $chosen | sed "s/\s$SEPARATOR.*//")
url=$(echo $chosen | sed "s/.*\($SEPARATOR\)\s//")

# perform action
if [ $1 = "--clipboard" ]; then
    echo "$url" | wl-copy
    notify-send -i 'none' "Clipboard content" "$url"
    # we dont alter history when copying to clipboard
    exit 0
elif [ "$1" = "-h" ] || [ "$1" = "--handler" ]; then
    # run all remaining arguments
    shift
    "$@" "$url"
else
    mpv "$url"
fi

# remove picked line from history and add it to beginning
cat $HISTORY | awk -vLine="$chosen" '!index($0,Line)' > /tmp/history
cat /tmp/history > $HISTORY
echo "$chosen" >> $HISTORY
